"""Tests for the core managed file store API."""

from __future__ import annotations

import os
from uuid import UUID, uuid4

import pytest

from star.core.files import (
    InvalidFileListCursorError,
    InvalidManagedFileMetadataError,
    LocalManagedFileStore,
    ManagedFilePreconditionFailedError,
    build_file_list_query,
    get_blob_path,
    iter_file_chunks,
    load_file_metadata,
    metadata_etag,
    sanitize_download_filename,
)


def test_local_store_creates_pending_and_finalizes_generated_file(settings):
    """
    GIVEN a local managed file store rooted in an isolated STAR directory
    WHEN a generated output placeholder is created and finalized
    THEN metadata and blob lifecycle state are published through the store API
    """

    store = LocalManagedFileStore(settings)

    placeholder = store.create_pending_output(original_filename="action.out.bin")
    blob_path = store.resolve_local_blob_path(placeholder.id)
    blob_path.write_bytes(b"generated bytes")

    metadata = store.finalize_generated_file(
        file_id=placeholder.id,
        original_filename="action.out.bin",
    )

    assert metadata.id == placeholder.id
    assert metadata.status == "ready"
    assert metadata.original_filename == "action.out.bin"
    assert metadata.size_bytes == len(b"generated bytes")
    assert load_file_metadata(metadata.id, settings) == metadata


def test_local_store_resolves_content_descriptor_for_ready_file(settings):
    """
    GIVEN a ready managed file created from trusted producer bytes
    WHEN content is resolved through the local managed file store
    THEN the descriptor owns the verified blob stream and safe download metadata
    """

    store = LocalManagedFileStore(settings)
    metadata = store.create_ready_file_from_bytes(
        original_filename="../report.txt",
        content=b"hello",
        extension=".txt",
        mime_type="text/plain",
    )

    descriptor = store.resolve_content(metadata.id)

    try:
        assert descriptor.file_id == metadata.id
        assert descriptor.stream.read() == b"hello"
        assert descriptor.mime_type == "text/plain"
        assert descriptor.filename == "report.txt"
        assert descriptor.size_bytes == 5
    finally:
        descriptor.stream.close()


def test_local_store_continues_opaque_cursor_with_changed_page_size(settings):
    """
    GIVEN ready managed files and a cursor issued for an unfiltered query
    WHEN the local store continues the same query with a different page size
    THEN it returns the remaining files without exposing decoded cursor state
    """

    store = LocalManagedFileStore(settings)
    metadata = [
        store.create_ready_file_from_bytes(
            original_filename=f"report-{index}.txt",
            content=f"report-{index}".encode("ascii"),
            extension=".txt",
            mime_type="text/plain",
        )
        for index in range(3)
    ]

    first_page = store.list_files(
        build_file_list_query(
            limit=1,
            cursor=None,
            sort="created_at",
            order="asc",
            status=None,
            mime_type=None,
            extension=None,
            file_name=None,
            tags=None,
        )
    )
    second_page = store.list_files(
        build_file_list_query(
            limit=2,
            cursor=first_page.next_cursor,
            sort="created_at",
            order="asc",
            status=None,
            mime_type=None,
            extension=None,
            file_name=None,
            tags=None,
        )
    )
    expected = sorted(metadata, key=lambda item: (item.created_at, item.id))

    assert [item.id for item in first_page.files] == [expected[0].id]
    assert [item.id for item in second_page.files] == [
        expected[1].id,
        expected[2].id,
    ]
    assert second_page.next_cursor is None


def test_local_store_rejects_cursor_from_different_query_context(settings):
    """
    GIVEN ready managed files and a cursor issued for an unfiltered query
    WHEN the local store receives it with a different status filter
    THEN it raises the focused cursor-domain error before pagination
    """

    store = LocalManagedFileStore(settings)
    for index in range(2):
        store.create_ready_file_from_bytes(
            original_filename=f"report-{index}.txt",
            content=f"report-{index}".encode("ascii"),
            extension=".txt",
            mime_type="text/plain",
        )
    first_page = store.list_files(
        build_file_list_query(
            limit=1,
            cursor=None,
            sort="created_at",
            order="asc",
            status=None,
            mime_type=None,
            extension=None,
            file_name=None,
            tags=None,
        )
    )

    with pytest.raises(InvalidFileListCursorError):
        store.list_files(
            build_file_list_query(
                limit=1,
                cursor=first_page.next_cursor,
                sort="created_at",
                order="asc",
                status="ready",
                mime_type=None,
                extension=None,
                file_name=None,
                tags=None,
            )
        )


def test_local_store_filters_editable_names_and_tags_with_cursor_context(settings):
    """
    GIVEN managed files with independently updated display names and tags
    WHEN the local store lists a filtered query and its cursor is reused
    THEN matching uses canonical metadata and changing tags rejects continuation
    """

    store = LocalManagedFileStore(settings)
    first = store.create_ready_file_from_bytes(
        original_filename="source-alpha.txt",
        content=b"alpha",
        extension=".txt",
        mime_type="text/plain",
    )
    second = store.create_ready_file_from_bytes(
        original_filename="source-beta.txt",
        content=b"beta",
        extension=".txt",
        mime_type="text/plain",
    )
    first = store.update_metadata(
        first.id,
        file_name="Quarterly Report.txt",
        tags=("finance", "q3"),
        expected_etag=metadata_etag(first),
    ).metadata
    store.update_metadata(
        second.id,
        file_name="Annual Report.txt",
        tags=("finance",),
        expected_etag=metadata_etag(second),
    )

    page = store.list_files(
        build_file_list_query(
            limit=1,
            cursor=None,
            sort="created_at",
            order="asc",
            status=None,
            mime_type=None,
            extension=None,
            file_name="report",
            tags="finance",
        )
    )

    assert page.files
    assert page.files[0].file_name.endswith("Report.txt")
    assert page.next_cursor is not None

    with pytest.raises(InvalidFileListCursorError):
        store.list_files(
            build_file_list_query(
                limit=1,
                cursor=page.next_cursor,
                sort="created_at",
                order="asc",
                status=None,
                mime_type=None,
                extension=None,
                file_name="report",
                tags="finance,q3",
            )
        )

    continued = store.list_files(
        build_file_list_query(
            limit=2,
            cursor=page.next_cursor,
            sort="created_at",
            order="asc",
            status=None,
            mime_type=None,
            extension=None,
            file_name="REPORT",
            tags="finance",
        )
    )

    expected_remaining = {first.id, second.id} - {page.files[0].id}
    assert {item.id for item in continued.files} == expected_remaining


def test_local_store_missing_metadata_raises_domain_error(settings):
    """
    GIVEN a local managed file store with no metadata for a UUID
    WHEN metadata is required through the store API
    THEN a storage-domain error is raised instead of an HTTP error
    """

    from star.core.files import ManagedFileNotFoundError

    store = LocalManagedFileStore(settings)

    with pytest.raises(ManagedFileNotFoundError):
        store.require_metadata(uuid4())


def test_local_store_conditionally_replaces_editable_metadata(settings):
    """
    GIVEN a ready managed file and its current metadata ETag
    WHEN the store replaces the display name and complete tag set
    THEN immutable metadata remains unchanged and a new ETag is returned
    """

    store = LocalManagedFileStore(settings)
    metadata = store.create_ready_file_from_bytes(
        original_filename="report.txt",
        content=b"report body",
        extension=".txt",
        mime_type="text/plain",
    )

    result = store.update_metadata(
        metadata.id,
        file_name="quarterly-report.txt",
        tags=("Q3", "finance"),
        expected_etag=metadata_etag(metadata),
    )

    assert result.metadata.file_name == "quarterly-report.txt"
    assert result.metadata.tags == ["finance", "q3"]
    assert result.metadata.original_filename == metadata.original_filename
    assert result.metadata.sha256 == metadata.sha256
    assert result.etag != metadata_etag(metadata)
    assert load_file_metadata(metadata.id, settings) == result.metadata


def test_local_store_rejects_stale_metadata_etag(settings):
    """
    GIVEN a ready managed file and an obsolete ETag
    WHEN conditional metadata replacement is attempted
    THEN the store rejects it without modifying metadata
    """

    store = LocalManagedFileStore(settings)
    metadata = store.create_ready_file_from_bytes(
        original_filename="report.txt",
        content=b"report body",
        extension=".txt",
        mime_type="text/plain",
    )

    with pytest.raises(ManagedFilePreconditionFailedError):
        store.update_metadata(
            metadata.id,
            file_name="quarterly-report.txt",
            tags=("finance",),
            expected_etag='"' + "0" * 64 + '"',
        )

    assert load_file_metadata(metadata.id, settings) == metadata


def test_local_store_rejects_metadata_extension_change_as_domain_validation(
    settings,
):
    """
    GIVEN a ready managed file and its current ETag
    WHEN a conditional metadata update changes its trusted extension
    THEN the store raises a mapped domain validation error instead of leaking ValueError
    """

    store = LocalManagedFileStore(settings)
    metadata = store.create_ready_file_from_bytes(
        original_filename="report.txt",
        content=b"report body",
        extension=".txt",
        mime_type="text/plain",
    )

    with pytest.raises(InvalidManagedFileMetadataError):
        store.update_metadata(
            metadata.id,
            file_name="report.pdf",
            tags=(),
            expected_etag=metadata_etag(metadata),
        )

    assert load_file_metadata(metadata.id, settings) == metadata


def test_sanitize_download_filename_strips_path_and_control_characters():
    """
    GIVEN persisted filename metadata containing path and control characters
    WHEN the download filename is sanitized for response headers
    THEN only a safe basename display value is returned
    """

    file_id = UUID("00000000-0000-0000-0000-000000000123")

    filename = sanitize_download_filename("../bad\x00name.txt", file_id)

    assert filename == "badname.txt"


def test_sanitize_download_filename_uses_deterministic_fallback_for_empty_names():
    """
    GIVEN missing or unusable persisted filename metadata
    WHEN the download filename is sanitized for response headers
    THEN a deterministic UUID-based fallback filename is returned
    """

    file_id = UUID("00000000-0000-0000-0000-000000000123")

    assert sanitize_download_filename("...", file_id) == f"file_{file_id}.bin"
    assert sanitize_download_filename(None, file_id) == f"file_{file_id}.bin"


def test_iter_file_chunks_yields_fixed_size_chunks(tmp_path):
    """
    GIVEN a local file and an explicit chunk size
    WHEN managed file chunks are iterated
    THEN bytes are yielded in deterministic fixed-size chunks until EOF
    """

    path = tmp_path / "stream.bin"
    path.write_bytes(b"abcdefg")

    stream = path.open("rb")
    chunks = list(iter_file_chunks(stream, chunk_size=3))

    assert chunks == [b"abc", b"def", b"g"]
    assert stream.closed


def test_iter_file_chunks_rejects_non_positive_chunk_size(tmp_path):
    """
    GIVEN a local file and an invalid chunk size
    WHEN managed file chunks are iterated
    THEN the helper rejects the invalid streaming configuration
    """

    path = tmp_path / "stream.bin"
    path.write_bytes(b"abcdefg")

    stream = path.open("rb")
    with pytest.raises(ValueError, match="chunk_size must be > 0"):
        list(iter_file_chunks(stream, chunk_size=0))
    assert stream.closed


def test_local_store_stream_uses_verified_descriptor_after_path_replacement(settings):
    """
    GIVEN a content descriptor opened for a ready managed blob
    WHEN its pathname is atomically replaced before streaming begins
    THEN streaming returns bytes from the already verified descriptor
    """

    store = LocalManagedFileStore(settings)
    metadata = store.create_ready_file_from_bytes(
        original_filename="report.txt",
        content=b"original bytes",
        extension=".txt",
        mime_type="text/plain",
    )
    descriptor = store.resolve_content(metadata.id)
    replacement = get_blob_path(metadata.id, settings).with_suffix(".replacement")
    replacement.write_bytes(b"replacement bytes")

    os.replace(replacement, get_blob_path(metadata.id, settings))
    chunks = list(iter_file_chunks(descriptor.stream, chunk_size=7))

    assert b"".join(chunks) == b"original bytes"
    assert descriptor.stream.closed
