"""Tests for the core managed file store API."""

from __future__ import annotations

from uuid import uuid4

import pytest

from star.core.files import (
    LocalManagedFileStore,
    get_blob_path,
    load_file_metadata,
)


def test_local_store_creates_pending_and_finalizes_generated_file(settings):
    """
    GIVEN a local managed file store rooted in an isolated STAR directory
    WHEN a generated output placeholder is created and finalized
    THEN metadata and blob lifecycle state are published through the store API
    """

    store = LocalManagedFileStore(settings)

    placeholder = store.create_pending_output(original_filename="action.out.bin")
    blob_path = store.resolve_local_blob_path(placeholder.id)
    blob_path.write_bytes(b"generated bytes")

    metadata = store.finalize_generated_file(
        file_id=placeholder.id,
        original_filename="action.out.bin",
    )

    assert metadata.id == placeholder.id
    assert metadata.status == "ready"
    assert metadata.original_filename == "action.out.bin"
    assert metadata.size_bytes == len(b"generated bytes")
    assert load_file_metadata(metadata.id, settings) == metadata


def test_local_store_resolves_content_descriptor_for_ready_file(settings):
    """
    GIVEN a ready managed file created from trusted producer bytes
    WHEN content is resolved through the local managed file store
    THEN the descriptor contains the local blob path and safe download metadata
    """

    store = LocalManagedFileStore(settings)
    metadata = store.create_ready_file_from_bytes(
        original_filename="../report.txt",
        content=b"hello",
        extension=".txt",
        mime_type="text/plain",
    )

    descriptor = store.resolve_content(metadata.id)

    assert descriptor.file_id == metadata.id
    assert descriptor.blob_path == get_blob_path(metadata.id, settings)
    assert descriptor.blob_path.read_bytes() == b"hello"
    assert descriptor.mime_type == "text/plain"
    assert descriptor.filename == "report.txt"
    assert descriptor.size_bytes == 5


def test_local_store_missing_metadata_raises_domain_error(settings):
    """
    GIVEN a local managed file store with no metadata for a UUID
    WHEN metadata is required through the store API
    THEN a storage-domain error is raised instead of an HTTP error
    """

    from star.core.files import ManagedFileNotFoundError

    store = LocalManagedFileStore(settings)

    with pytest.raises(ManagedFileNotFoundError):
        store.require_metadata(uuid4())
